name: Build and Deploy Community Blog
on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: mbaza/community.blog

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}
          #Use branch, short sha and latest as tags
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push-image
    runs-on: blog
    steps:
      - uses: actions/checkout@v3
      - name: Copy files to the server
        env:
            ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env
          mkdir -p ~/community.blog
          cp docker-compose.yaml ~/community.blog
          cp .env ~/community.blog
          cd ~/community.blog
          docker network ls|grep blog_net > /dev/null || docker network create --driver bridge blog_net
          docker-compose down --rmi all -v --remove-orphans
          docker-compose up -d